spring.application.name=saidika
spring.datasource.url=jdbc:postgresql://localhost:5432/saidika
spring.datasource.username=postgres
spring.datasource.password=123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true